url: "http://anatolypet21.github.io/wedding-theme" # the base hostname & protocol for your site
#url: "http://127.0.0.1:4000"
#baseurl: "http://anatolypet21.github.io/wedding-theme"
baseurl: ""
markdown: kramdown

include: ['_pages']

# jekyll-sitemap generate sitemap.xml at _site/ dir. It helps google search webmaster to index the website
# jekyll-feed The plugin will automatically generate an Atom feed at /feed.xml.

# HOW TO INSTALL - >  sudo gem install jekyll-sitemap jekyll-feed
gems: [jekyll-sitemap,jekyll-feed,jekyll-paginate]


# how many post to show in ALL POST and FEATURED POST
paginate: 4

paginate_path: "/blog/page:num/"

permalink: /:title
