url: "http://anatolypet21.github.io/wedding-theme/" # the base hostname & protocol for your site
#url: "http://127.0.0.1:4000"
markdown: kramdown

include: ['_pages']

# jekyll-sitemap generate sitemap.xml at _site/ dir. It helps google search webmaster to index the website
# jekyll-feed The plugin will automatically generate an Atom feed at /feed.xml.

# HOW TO INSTALL - >  sudo gem install jekyll-sitemap jekyll-feed
gems: [jekyll-sitemap,jekyll-feed,jekyll-paginate,jekyll-archives,jekyll-assets,algoliasearch-jekyll]
algolia:
  application_id: 'OESQP1EJVV'
  index_name: 'wedding-theme'
  read_only_api_key: 'fd716e7bf911ce99c90728284d3eb4ea'
  excluded_files:
    - 404.html
    - index.html
  settings:
    attributeForDistinct: 'hierarchy'
    distinct: true
    attributesToSnippet: ['text:20']
    attributesToIndex:
      - title
      - h1
      - h2
      - h3
      - h4
      - h5
      - h6
      - unordered(text)
      - unordered(tags)
    
# how many post to show in ALL POST and FEATURED POST
paginate: 6

paginate_path: "/blog/page:num/"

jekyll-archives:
  enabled:
    - year
    - month
    - categories
    - tags
  layouts:
    year: archive-time
    month: archive-time
  permalinks:
    year: '/:year/'
    month: '/:year/:month/'
    day: '/:year/:month/:day/'
    tag: '/tag/:name/'
    category: '/category/:name/'

assets:
  compress:
    css: true
    js: true
  cache: .asset-cache
  cdn: https://cdn.example.com
  skip_baseurl_with_cdn: false
  skip_prefix_with_cdn: false
  prefix: "/assets"
  assets:
    - "*.png"
    - "bundle.css"
  digest: true
  sources:
    - _assets/sass
    - _assets/images/post
    - _assets/libs
    - _assets/stylesheets
    - _assets/fonts
    - _assets/libs/slick-1.5.9
  features:
    liquid: true
    automatic_img_size: true
    automatic_img_alt : true
